export default [
  ['Guardian', 'Savant', 'Skiltvakten'],
  ['Warder', 'Consantoir', 'Isen Vakten'],
  ['Myrmidon', 'Brehon', 'Flammen Vakten'],
  ['Gryphon Knight', 'Grove Protector', 'Elding Vakten'],
  ['Eagle Knight', 'Raven Ardent', 'Stormur Vakten'],
  ['Phoenix Knight', 'Silver Hand', 'Isen Herra'],
  ['Alerion Knight', 'Thunderer', 'Flammen Herra'],
  ['Unicorn Knight', 'Gilded Spear', 'Elding Herra'],
  ['Lion Knight', 'Tiarna', 'Bantiarna', 'Stormur Herra'],
  ['Dragon Knight', 'Emerald Ridere', 'Einherjar'],
  ['Lord', 'Lady', 'Barun', 'Banbharun', 'Herra', 'Fru'],
  ['Baronet', 'Baronetess', 'Ard Tiarna', 'Ard Bantiarna', 'Hersir', 'Baronsfru'],
  ['Baron', 'Baroness', 'Ciann', 'Cath', 'Vicomte', 'Vicomtessa'],
  ['Arch Duke', 'Arch Duchess', 'Ard Diuc', 'Ard Bandiuc', 'Stor Jarl', 'Stor Hurfru'],
]
